/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('Rolodex.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Rolodex"
        castShadow
        receiveShadow
        geometry={nodes.Rolodex.geometry}
        material={materials.White_Plastic_Shell}
        position={[-1.35, -0.33, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Rolodex_rolltop"
        castShadow
        receiveShadow
        geometry={nodes.Rolodex_rolltop.geometry}
        material={materials.Clear_Plastic_Top}
        position={[-0.96, 0.95, -1.07]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Rolodex_leaflet_1"
        castShadow
        receiveShadow
        geometry={nodes.Rolodex_leaflet_1.geometry}
        material={nodes.Rolodex_leaflet_1.material}
        position={[-0.5, 0.41, -1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Rolodex_leaflet_2"
        castShadow
        receiveShadow
        geometry={nodes.Rolodex_leaflet_2.geometry}
        material={nodes.Rolodex_leaflet_2.material}
        position={[-0.5, 0.41, -1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Rolodex_leaflet_3"
        castShadow
        receiveShadow
        geometry={nodes.Rolodex_leaflet_3.geometry}
        material={nodes.Rolodex_leaflet_3.material}
        position={[-0.5, 0.41, -1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rolodex_leaflet_4.geometry}
        material={nodes.Rolodex_leaflet_4.material}
        position={[-0.5, 0.41, -1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Rolodex_leaflets"
        castShadow
        receiveShadow
        geometry={nodes.Rolodex_leaflets.geometry}
        material={nodes.Rolodex_leaflets.material}
        position={[-0.5, 0.41, -1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/Rolodex.glb')